/// @description FNAFN Obj_Menu_Continue / KeyPress - PARTIALLY PORTED (KeyPress_81)
// Original GML was YYC-compiled into FNAFN.exe. The C below is the exact
// machine-level semantics recovered by Ghidra. Porting task: express this
// in GML. Call graph and names are intact (see gml_all_414_decompiled.c).
// 4 sub-event(s): KeyPress_69, KeyPress_81, KeyPress_83, KeyPress_87
//  (regenerated by fill_keymouse_stubs.py; KeyPress_81 ported in place)

// ---- sub-event KeyPress_69 - NOT YET PORTED ----
// ground truth: gml_Object_Obj_Menu_Continue_KeyPress_69 (921 B @0x140055ff0)
/* BEGIN DECOMPILED REFERENCE
void gml_Object_Obj_Menu_Continue_KeyPress_69(longlong *param_1,undefined8 param_2)

{
  int iVar1;
  undefined8 uVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  undefined8 *puStack_108;
  undefined8 *puStack_100;
  undefined8 *puStack_f8;
  undefined8 *puStack_f0;
  undefined8 uStack_e0;
  uint uStack_d4;
  undefined8 uStack_d0;
  uint uStack_c4;
  undefined8 uStack_c0;
  undefined *puStack_b8;
  undefined4 uStack_b0;
  undefined8 uStack_a8;
  uint uStack_9c;
  undefined8 uStack_98;
  uint uStack_8c;
  undefined8 uStack_88;
  uint uStack_7c;
  undefined8 uStack_78;
  uint uStack_6c;
  undefined8 uStack_60;
  undefined4 uStack_54;
  undefined8 uStack_50;
  undefined4 uStack_48;
  uint uStack_44;
  undefined8 uStack_40;
  
  uStack_40 = 0xfffffffffffffffe;
  puStack_b8 = &UNK_14043aa4e;
  uStack_c0 = puRam0000000140657668;
  puRam0000000140657668 = &uStack_c0;
  uStack_9c = 0xffffff;
  uStack_a8 = 0;
  uStack_8c = 0xffffff;
  uStack_98 = 0;
  uStack_7c = 0xffffff;
  uStack_88 = 0;
  uStack_6c = 0xffffff;
  uStack_78 = 0;
  uStack_44 = 0xffffff;
  uStack_50 = 0;
  uStack_d4 = 0xffffff;
  uStack_e0 = 0;
  uStack_c4 = 0xffffff;
  uStack_d0 = 0;
  uStack_b0 = 1;
  plRam0000000140657680 = param_1;
  uVar2 = (**(code **)(*param_1 + 8))(param_1,0x18712);
  uStack_54 = 0;
  uStack_60 = 0x3fef333333333333;
  iVar1 = func_0x00014015be60(uVar2,&uStack_60,uRam00000001405cd9c0,1);
  if (0 < iVar1) {
    uStack_b0 = 3;
    uVar2 = (**(code **)(*param_1 + 8))(param_1,0x1876a);
    uStack_54 = 0;
    uStack_60 = 0x4018000000000000;
    uVar3 = (undefined4)uRam00000001405cd9c0;
    uVar4 = (undefined4)((ulonglong)uRam00000001405cd9c0 >> 0x20);
    iVar1 = func_0x00014015be60(uVar2,&uStack_60,uRam00000001405cd9c0,0);
    if (iVar1 == 0) {
      uStack_b0 = 5;
      if ((0x46U >> (uStack_44 & 0x1f) & 1) != 0) {
        func_0x000140001410(&uStack_50);
      }
      uStack_50 = 0;
      uStack_48 = 0;
      uStack_44 = 5;
      func_0x00014000bee0(&uStack_a8,0x140655570);
      puStack_108 = &uStack_a8;
      func_0x0001401445d0(param_1,param_2,&uStack_50,1,uRam00000001405c8cb0,&puStack_108);
      uVar3 = (undefined4)uRam00000001405cd9c0;
      uVar4 = (undefined4)((ulonglong)uRam00000001405cd9c0 >> 0x20);
    }
    uStack_b0 = 7;
    uStack_54 = 0;
    uStack_60 = 0x401c000000000000;
    iVar1 = func_0x00014015be60(uVar2,&uStack_60,CONCAT44(uVar4,uVar3),0);
    if (iVar1 == 0) {
      uStack_b0 = 9;
      if ((0x46U >> (uStack_44 & 0x1f) & 1) != 0) {
        func_0x000140001410(&uStack_50);
      }
      uStack_50 = 0;
      uStack_48 = 0;
      uStack_44 = 5;
      (**(code **)(*param_1 + 8))(param_1,0x1876a);
      func_0x00014000bee0(&uStack_a8,0x1405c3d58);
      puStack_108 = &uStack_a8;
      func_0x00014000bee0(&uStack_98,0x1405c3d68);
      puStack_100 = &uStack_98;
      if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
        func_0x000140001410(&uStack_88);
      }
      func_0x0001401441e0(&uStack_88,0x1405c3d48);
      puStack_f8 = &uStack_88;
      func_0x00014000bee0(&uStack_78,0x1405c3d78);
      puStack_f0 = &uStack_78;
      func_0x0001401445d0(param_1,param_2,&uStack_50,4,uRam00000001405c8d90,&puStack_108);
      uStack_b0 = 10;
      func_0x00014017c070(param_1,param_2,0,0);
    }
  }
  if ((0x46U >> (uStack_c4 & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_d0);
  }
  if ((0x46U >> (uStack_d4 & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_e0);
  }
  if ((0x46U >> (uStack_44 & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_50);
  }
  if ((0x46U >> (uStack_6c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_78);
  }
  if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_88);
  }
  if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_98);
  }
  if ((0x46U >> (uStack_9c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_a8);
  }
  puRam0000000140657668 = (undefined8 *)uStack_c0;
  return;
}
END DECOMPILED REFERENCE */

// ---- sub-event KeyPress_81 (Q) - PORTED from C ----
// Ground truth: gml_Object_Obj_Menu_Continue_KeyPress_81 (530 B @0x140052a80)
// Decoded (uStack_a0 = 1/3 are GML line markers):
//   1. line 1: 4-arg call on slot uRam00000001405c8d90 (REGISTRY-CONFIRMED
//      instance_create_layer), args staged in order:
//        x = exe const 0x1405c3cf8 = 32.0
//        y = exe const 0x1405c3d08 = 160.0
//        layer = exe string 0x1405c3ce8 = "Main_menu"
//        object = exe const 0x1405c3d18 = 63.0 -> obj_names.json index 63
//                 = Obj_Menu_Main_Title
//   2. line 3: no-arg room service func_0x00014017c070(self, other, 0, 0)
//      (best fit room_goto_next, 49 sites repo-wide).
// Reading: Q on the night-select screen spawns the main-title object on
// the Main_menu layer at (32, 160) and advances the room -- the "back to
// main menu" key.
instance_create_layer(32, 160, "Main_menu", Obj_Menu_Main_Title);
// TODO(calibrate): helper 0x14017c070(self, other, 0, 0) - no-arg
// room/event service; best fit room_goto_next() (49 sites repo-wide).
room_goto_next();

/* BEGIN DECOMPILED REFERENCE
void gml_Object_Obj_Menu_Continue_KeyPress_81(undefined8 param_1,undefined8 param_2)

{
  undefined8 *puStack_d8;
  undefined8 *puStack_d0;
  undefined8 *puStack_c8;
  undefined8 *puStack_c0;
  undefined8 uStack_b0;
  undefined *puStack_a8;
  undefined4 uStack_a0;
  undefined8 uStack_98;
  uint uStack_8c;
  undefined8 uStack_88;
  uint uStack_7c;
  undefined8 uStack_78;
  undefined8 uStack_70;
  undefined8 uStack_68;
  uint uStack_5c;
  undefined8 uStack_58;
  uint uStack_4c;
  undefined8 uStack_48;
  uint uStack_3c;
  undefined8 uStack_38;
  uint uStack_2c;
  undefined8 uStack_28;
  
  uStack_28 = 0xfffffffffffffffe;
  puStack_a8 = &UNK_14043a9d3;
  uStack_b0 = puRam0000000140657668;
  puRam0000000140657668 = &uStack_b0;
  uStack_5c = 0xffffff;
  uStack_68 = 0;
  uStack_4c = 0xffffff;
  uStack_58 = 0;
  uStack_3c = 0xffffff;
  uStack_48 = 0;
  uStack_2c = 0xffffff;
  uStack_38 = 0;
  uStack_8c = 0xffffff;
  uStack_98 = 0;
  uStack_7c = 0xffffff;
  uStack_88 = 0;
  uStack_a0 = 1;
  uStack_78 = 0;
  uStack_70 = 0x500000000;
  uRam0000000140657680 = param_1;
  func_0x00014000bee0(&uStack_68,0x1405c3cf8);
  puStack_d8 = &uStack_68;
  func_0x00014000bee0(&uStack_58,0x1405c3d08);
  puStack_d0 = &uStack_58;
  if ((0x46U >> (uStack_3c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_48);
  }
  func_0x0001401441e0(&uStack_48,0x1405c3ce8);
  puStack_c8 = &uStack_48;
  func_0x00014000bee0(&uStack_38,0x1405c3d18);
  puStack_c0 = &uStack_38;
  func_0x0001401445d0(param_1,param_2,&uStack_78,4,uRam00000001405c8d90,&puStack_d8);
  uStack_a0 = 3;
  func_0x00014017c070(param_1,param_2,0,0);
  if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_88);
  }
  if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_98);
  }
  if ((0x46U >> (uStack_70._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_78);
  }
  if ((0x46U >> (uStack_2c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_38);
  }
  if ((0x46U >> (uStack_3c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_48);
  }
  if ((0x46U >> (uStack_4c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_58);
  }
  if ((0x46U >> (uStack_5c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_68);
  }
  puRam0000000140657668 = (undefined8 *)uStack_b0;
  return;
}
END DECOMPILED REFERENCE */

// ---- sub-event KeyPress_83 - NOT YET PORTED ----
// ground truth: gml_Object_Obj_Menu_Continue_KeyPress_83 (4462 B @0x140052e60)
/* BEGIN DECOMPILED REFERENCE
void gml_Object_Obj_Menu_Continue_KeyPress_83(longlong *param_1,undefined8 param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined8 uVar3;
  undefined8 uVar4;
  uint in_stack_fffffffffffffe68;
  uint uVar5;
  ulonglong in_stack_fffffffffffffe70;
  undefined8 **ppuVar6;
  undefined8 uStack_188;
  uint uStack_17c;
  undefined8 *puStack_178;
  undefined8 *puStack_170;
  undefined8 *puStack_168;
  undefined8 *puStack_160;
  undefined8 uStack_158;
  uint uStack_14c;
  undefined8 uStack_148;
  uint uStack_13c;
  undefined8 uStack_138;
  uint uStack_12c;
  undefined8 uStack_128;
  uint uStack_11c;
  undefined8 uStack_118;
  undefined8 uStack_110;
  uint uStack_104;
  undefined8 uStack_100;
  undefined8 uStack_f8;
  undefined8 uStack_f0;
  undefined auStack_e8 [8];
  undefined8 uStack_e0;
  undefined8 uStack_d0;
  undefined8 uStack_c8;
  undefined8 uStack_c0;
  undefined *puStack_b8;
  undefined4 uStack_b0;
  undefined8 uStack_a8;
  uint uStack_9c;
  undefined8 uStack_98;
  uint uStack_8c;
  undefined8 uStack_88;
  uint uStack_7c;
  undefined auStack_78 [8];
  undefined8 uStack_70;
  undefined8 uStack_60;
  
  uStack_60 = 0xfffffffffffffffe;
  puStack_b8 = &UNK_14043a9fc;
  uStack_b0 = 0;
  uStack_c0 = puRam0000000140657668;
  puRam0000000140657668 = &uStack_c0;
  uStack_14c = 0xffffff;
  uStack_158 = 0;
  uStack_13c = 0xffffff;
  uStack_148 = 0;
  uStack_12c = 0xffffff;
  uStack_138 = 0;
  uStack_11c = 0xffffff;
  uStack_128 = 0;
  uStack_8c = 0xffffff;
  uStack_98 = 0;
  uStack_7c = 0xffffff;
  uStack_88 = 0;
  uStack_104 = 0xffffff;
  uStack_110 = 0;
  plRam0000000140657680 = param_1;
  uStack_100 = param_2;
  uStack_118 = (**(code **)(*plRam000000014065e080 + 8))(plRam000000014065e080,0x1870b);
  uStack_c8 = CONCAT44(0xffffff,(undefined4)uStack_c8);
  uStack_d0 = 0;
  uStack_f0 = CONCAT44(0xffffff,(undefined4)uStack_f0);
  uStack_f8 = 0;
  uStack_17c = 0xffffff;
  uStack_188 = 0;
  uStack_b0 = 1;
  uVar3 = (**(code **)(*param_1 + 8))(param_1,0x1876a);
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x401c000000000000;
  uVar2 = (undefined4)uRam00000001405cd9c0;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,1);
  if ((iVar1 != -2) && (iVar1 < 0)) {
    uStack_b0 = 2;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    func_0x00014000bf90(uVar3,1);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 5;
  _auStack_78 = ZEXT416(SUB124(_auStack_78,8)) << 0x40;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 7;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4072700000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 8;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 9;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0xc;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x3ff0000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0xe;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4075400000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0xf;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x3ff0000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x10;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x13;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x4000000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x15;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4078100000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x16;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x4000000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x17;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x1a;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x4008000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x1c;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x407ae00000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x1d;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x4008000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x1e;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x21;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x4010000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x23;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x407db00000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x24;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x4010000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x25;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x28;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x4014000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x2a;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4080400000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x2b;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x4014000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x2c;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x2f;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x4018000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x31;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4081a80000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x32;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x4018000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x33;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x36;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x401c000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x38;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4083100000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x39;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x401c000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x3a;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
  }
  uStack_b0 = 0x3d;
  if ((0x46U >> (uStack_c8._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_d0);
  }
  uStack_d0 = 0;
  uStack_c8 = 0x500000000;
  _auStack_78 = ZEXT816(0);
  func_0x000140144a40(0x23,uRam00000001405c7b88,0x80000000,&uStack_110);
  func_0x000140160480(0x23,0x1876d,0x80000000,auStack_78,in_stack_fffffffffffffe68 & 0xffffff00,
                      in_stack_fffffffffffffe70 & 0xffffffffffffff00);
  func_0x000140001490(&uStack_158,&uStack_110);
  puStack_178 = &uStack_158;
  func_0x000140001490(&uStack_148,auStack_78);
  uStack_e0._4_4_ = 0;
  uStack_e0._0_4_ = SUB124(_auStack_e8,8);
  auStack_e8 = (undefined  [8])0x3fc999999999999a;
  puStack_170 = &uStack_148;
  func_0x0001400053f0(auStack_e8,uStack_118);
  func_0x000140001490(&uStack_138,auStack_e8);
  if ((0x46U >> (uStack_e0._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(auStack_e8);
  }
  ppuVar6 = &puStack_178;
  uVar5 = uRam00000001405c8cc0;
  puStack_168 = &uStack_138;
  uVar4 = func_0x0001401445d0(param_1,uStack_100,&uStack_d0,3,uRam00000001405c8cc0,ppuVar6);
  func_0x000140001490(&uStack_110,uVar4);
  func_0x00014015fea0(0x23,uRam00000001405c7b88,0x80000000,&uStack_110);
  uStack_b0 = 0x3e;
  if ((0x46U >> (uStack_c8._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_d0);
  }
  uStack_d0 = 0;
  uStack_c8 = 0x500000000;
  if ((0x46U >> (uStack_f0._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_f8);
  }
  uStack_f8 = 0;
  uStack_f0 = 0x500000000;
  _auStack_e8 = ZEXT816(0);
  uVar4 = (**(code **)(*param_1 + 8))(param_1,0x1878c);
  func_0x000140160480(0x23,0x18769,0x80000000,auStack_e8,uVar5 & 0xffffff00,
                      (ulonglong)ppuVar6 & 0xffffffffffffff00);
  uVar2 = func_0x00014012cd90(uVar3);
  uVar3 = func_0x00014002fbe0(uVar4,uVar2);
  func_0x000140001490(&uStack_158,uVar3);
  puStack_178 = &uStack_158;
  func_0x000140001490(&uStack_148,auStack_e8);
  puStack_170 = &uStack_148;
  uVar3 = func_0x0001401445d0(param_1,uStack_100,&uStack_f8,1,uRam00000001405c8d80,&puStack_178);
  uStack_9c = 0;
  uStack_a8 = 0x4057800000000000;
  func_0x000140005290(&uStack_a8,uVar3);
  func_0x000140001490(&uStack_138,&uStack_a8);
  if ((0x46U >> (uStack_9c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_a8);
  }
  uStack_9c = 0;
  uStack_a8 = 0x3fc999999999999a;
  puStack_168 = &uStack_138;
  func_0x0001400053f0(&uStack_a8,uStack_118);
  func_0x000140001490(&uStack_128,&uStack_a8);
  if ((0x46U >> (uStack_9c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_a8);
  }
  puStack_160 = &uStack_128;
  uVar3 = func_0x0001401445d0(param_1,uStack_100,&uStack_d0,3,uRam00000001405c8cc0,&puStack_170);
  uVar4 = func_0x000140160290(0x23);
  func_0x000140141d00(uVar4);
  func_0x000140001490(auStack_e8,uVar3);
  func_0x000140141c50(1);
  func_0x000140160b90(0x23,0x18769,0x80000000,auStack_e8);
  uStack_b0 = 0x40;
  if ((0x46U >> (uStack_c8._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_d0);
  }
  uStack_d0 = 0;
  uStack_c8 = 0x500000000;
  uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x18712);
  func_0x000140001490(&uStack_158,uVar3);
  puStack_178 = &uStack_158;
  func_0x00014000bee0(&uStack_148,0x1405c3d28);
  uStack_9c = 0;
  uStack_a8 = 0x3fa999999999999a;
  puStack_170 = &uStack_148;
  func_0x0001400053f0(&uStack_a8,uStack_118);
  func_0x000140001490(&uStack_138,&uStack_a8);
  if ((0x46U >> (uStack_9c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_a8);
  }
  puStack_168 = &uStack_138;
  uVar4 = func_0x0001401445d0(param_1,uStack_100,&uStack_d0,3,uRam00000001405c8cc0,&puStack_178);
  func_0x000140141d00(param_1);
  func_0x000140001490(uVar3,uVar4);
  func_0x000140141c50(1);
  if ((0x46U >> (uStack_17c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_188);
  }
  if ((0x46U >> (uStack_f0._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_f8);
  }
  if ((0x46U >> (uStack_c8._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_d0);
  }
  if ((0x46U >> (uStack_104 & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_110);
  }
  if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_88);
  }
  if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_98);
  }
  if ((0x46U >> (uStack_11c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_128);
  }
  if ((0x46U >> (uStack_12c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_138);
  }
  if ((0x46U >> (uStack_13c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_148);
  }
  if ((0x46U >> (uStack_14c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_158);
  }
  puRam0000000140657668 = (undefined8 *)uStack_c0;
  return;
}
END DECOMPILED REFERENCE */

// ---- sub-event KeyPress_87 - NOT YET PORTED ----
// ground truth: gml_Object_Obj_Menu_Continue_KeyPress_87 (4518 B @0x1400546c0)
/* BEGIN DECOMPILED REFERENCE
void gml_Object_Obj_Menu_Continue_KeyPress_87(longlong *param_1,undefined8 param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined8 uVar3;
  undefined8 uVar4;
  uint in_stack_fffffffffffffe68;
  uint uVar5;
  ulonglong in_stack_fffffffffffffe70;
  undefined8 **ppuVar6;
  undefined8 uStack_188;
  uint uStack_17c;
  undefined8 *puStack_178;
  undefined8 *puStack_170;
  undefined8 *puStack_168;
  undefined8 *puStack_160;
  undefined8 uStack_158;
  uint uStack_14c;
  undefined8 uStack_148;
  uint uStack_13c;
  undefined8 uStack_138;
  uint uStack_12c;
  undefined8 uStack_128;
  uint uStack_11c;
  undefined8 uStack_118;
  undefined8 uStack_110;
  uint uStack_104;
  undefined8 uStack_100;
  undefined8 uStack_f8;
  undefined8 uStack_f0;
  undefined auStack_e8 [8];
  undefined8 uStack_e0;
  undefined8 uStack_d0;
  undefined8 uStack_c8;
  undefined8 uStack_c0;
  undefined *puStack_b8;
  undefined4 uStack_b0;
  undefined8 uStack_a8;
  uint uStack_9c;
  undefined8 uStack_98;
  uint uStack_8c;
  undefined8 uStack_88;
  uint uStack_7c;
  undefined auStack_78 [8];
  undefined8 uStack_70;
  undefined8 uStack_60;
  
  uStack_60 = 0xfffffffffffffffe;
  puStack_b8 = &UNK_14043aa25;
  uStack_b0 = 0;
  uStack_c0 = puRam0000000140657668;
  puRam0000000140657668 = &uStack_c0;
  uStack_14c = 0xffffff;
  uStack_158 = 0;
  uStack_13c = 0xffffff;
  uStack_148 = 0;
  uStack_12c = 0xffffff;
  uStack_138 = 0;
  uStack_11c = 0xffffff;
  uStack_128 = 0;
  uStack_8c = 0xffffff;
  uStack_98 = 0;
  uStack_7c = 0xffffff;
  uStack_88 = 0;
  uStack_104 = 0xffffff;
  uStack_110 = 0;
  plRam0000000140657680 = param_1;
  uStack_100 = param_2;
  uStack_118 = (**(code **)(*plRam000000014065e080 + 8))(plRam000000014065e080,0x1870b);
  uStack_c8 = CONCAT44(0xffffff,(undefined4)uStack_c8);
  uStack_d0 = 0;
  uStack_f0 = CONCAT44(0xffffff,(undefined4)uStack_f0);
  uStack_f8 = 0;
  uStack_17c = 0xffffff;
  uStack_188 = 0;
  uStack_b0 = 1;
  uVar3 = (**(code **)(*param_1 + 8))(param_1,0x1876a);
  _auStack_78 = ZEXT416(SUB124(_auStack_78,8)) << 0x40;
  uVar2 = (undefined4)uRam00000001405cd9c0;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,1);
  if (0 < iVar1) {
    uStack_b0 = 3;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    uStack_70._4_4_ = 0;
    auStack_78 = (undefined  [8])0x3ff0000000000000;
    func_0x00014000bdb0(uVar3,auStack_78);
    if ((0x46U >> (uStack_70._4_4_ & 0x1f) & 1) != 0) {
      func_0x000140001410(auStack_78);
    }
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 5;
  _auStack_78 = ZEXT416(SUB124(_auStack_78,8)) << 0x40;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 7;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4072700000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 8;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 9;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0xc;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x3ff0000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0xe;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4075400000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0xf;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x3ff0000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x10;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x13;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x4000000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x15;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4078100000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x16;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x4000000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x17;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x1a;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x4008000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x1c;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x407ae00000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x1d;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x4008000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x1e;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x21;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x4010000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x23;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x407db00000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x24;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x4010000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x25;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x28;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x4014000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x2a;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4080400000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x2b;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x4014000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x2c;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x2f;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x4018000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x31;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4081a80000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x32;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x4018000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x33;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
    uVar2 = (undefined4)uRam00000001405cd9c0;
  }
  uStack_b0 = 0x36;
  uStack_70._4_4_ = 0;
  uStack_70._0_4_ = SUB124(_auStack_78,8);
  auStack_78 = (undefined  [8])0x401c000000000000;
  iVar1 = func_0x00014015be60(uVar3,auStack_78,uVar2,0);
  if (iVar1 == 0) {
    uStack_b0 = 0x38;
    uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x1876a);
    _auStack_78 = ZEXT816(0x4083100000000000);
    func_0x000140160b90(0x23,0x1876d,0x80000000,auStack_78);
    uStack_b0 = 0x39;
    if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_98);
    }
    uStack_8c = 0;
    uStack_98 = 0x401c000000000000;
    func_0x00014015fea0(0x1d,uRam00000001405c7aa8,0x80000000,&uStack_98);
    uStack_b0 = 0x3a;
    if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
      func_0x000140001410(&uStack_88);
    }
    uStack_7c = 0;
    uStack_88 = 0;
    func_0x00014015fea0(0x1d,uRam00000001405c7b98,0x80000000,&uStack_88);
  }
  uStack_b0 = 0x3d;
  if ((0x46U >> (uStack_c8._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_d0);
  }
  uStack_d0 = 0;
  uStack_c8 = 0x500000000;
  _auStack_78 = ZEXT816(0);
  func_0x000140144a40(0x23,uRam00000001405c7b88,0x80000000,&uStack_110);
  func_0x000140160480(0x23,0x1876d,0x80000000,auStack_78,in_stack_fffffffffffffe68 & 0xffffff00,
                      in_stack_fffffffffffffe70 & 0xffffffffffffff00);
  func_0x000140001490(&uStack_158,&uStack_110);
  puStack_178 = &uStack_158;
  func_0x000140001490(&uStack_148,auStack_78);
  uStack_e0._4_4_ = 0;
  uStack_e0._0_4_ = SUB124(_auStack_e8,8);
  auStack_e8 = (undefined  [8])0x3fc999999999999a;
  puStack_170 = &uStack_148;
  func_0x0001400053f0(auStack_e8,uStack_118);
  func_0x000140001490(&uStack_138,auStack_e8);
  if ((0x46U >> (uStack_e0._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(auStack_e8);
  }
  ppuVar6 = &puStack_178;
  uVar5 = uRam00000001405c8cc0;
  puStack_168 = &uStack_138;
  uVar4 = func_0x0001401445d0(param_1,uStack_100,&uStack_d0,3,uRam00000001405c8cc0,ppuVar6);
  func_0x000140001490(&uStack_110,uVar4);
  func_0x00014015fea0(0x23,uRam00000001405c7b88,0x80000000,&uStack_110);
  uStack_b0 = 0x3e;
  if ((0x46U >> (uStack_c8._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_d0);
  }
  uStack_d0 = 0;
  uStack_c8 = 0x500000000;
  if ((0x46U >> (uStack_f0._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_f8);
  }
  uStack_f8 = 0;
  uStack_f0 = 0x500000000;
  _auStack_e8 = ZEXT816(0);
  uVar4 = (**(code **)(*param_1 + 8))(param_1,0x1878c);
  func_0x000140160480(0x23,0x18769,0x80000000,auStack_e8,uVar5 & 0xffffff00,
                      (ulonglong)ppuVar6 & 0xffffffffffffff00);
  uVar2 = func_0x00014012cd90(uVar3);
  uVar3 = func_0x00014002fbe0(uVar4,uVar2);
  func_0x000140001490(&uStack_158,uVar3);
  puStack_178 = &uStack_158;
  func_0x000140001490(&uStack_148,auStack_e8);
  puStack_170 = &uStack_148;
  uVar3 = func_0x0001401445d0(param_1,uStack_100,&uStack_f8,1,uRam00000001405c8d80,&puStack_178);
  uStack_9c = 0;
  uStack_a8 = 0x4057800000000000;
  func_0x000140005290(&uStack_a8,uVar3);
  func_0x000140001490(&uStack_138,&uStack_a8);
  if ((0x46U >> (uStack_9c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_a8);
  }
  uStack_9c = 0;
  uStack_a8 = 0x3fc999999999999a;
  puStack_168 = &uStack_138;
  func_0x0001400053f0(&uStack_a8,uStack_118);
  func_0x000140001490(&uStack_128,&uStack_a8);
  if ((0x46U >> (uStack_9c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_a8);
  }
  puStack_160 = &uStack_128;
  uVar3 = func_0x0001401445d0(param_1,uStack_100,&uStack_d0,3,uRam00000001405c8cc0,&puStack_170);
  uVar4 = func_0x000140160290(0x23);
  func_0x000140141d00(uVar4);
  func_0x000140001490(auStack_e8,uVar3);
  func_0x000140141c50(1);
  func_0x000140160b90(0x23,0x18769,0x80000000,auStack_e8);
  uStack_b0 = 0x40;
  if ((0x46U >> (uStack_c8._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_d0);
  }
  uStack_d0 = 0;
  uStack_c8 = 0x500000000;
  uVar3 = (**(code **)(*param_1 + 0x10))(param_1,0x18712);
  func_0x000140001490(&uStack_158,uVar3);
  puStack_178 = &uStack_158;
  func_0x00014000bee0(&uStack_148,0x1405c3d38);
  uStack_9c = 0;
  uStack_a8 = 0x3fa999999999999a;
  puStack_170 = &uStack_148;
  func_0x0001400053f0(&uStack_a8,uStack_118);
  func_0x000140001490(&uStack_138,&uStack_a8);
  if ((0x46U >> (uStack_9c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_a8);
  }
  puStack_168 = &uStack_138;
  uVar4 = func_0x0001401445d0(param_1,uStack_100,&uStack_d0,3,uRam00000001405c8cc0,&puStack_178);
  func_0x000140141d00(param_1);
  func_0x000140001490(uVar3,uVar4);
  func_0x000140141c50(1);
  if ((0x46U >> (uStack_17c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_188);
  }
  if ((0x46U >> (uStack_f0._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_f8);
  }
  if ((0x46U >> (uStack_c8._4_4_ & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_d0);
  }
  if ((0x46U >> (uStack_104 & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_110);
  }
  if ((0x46U >> (uStack_7c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_88);
  }
  if ((0x46U >> (uStack_8c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_98);
  }
  if ((0x46U >> (uStack_11c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_128);
  }
  if ((0x46U >> (uStack_12c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_138);
  }
  if ((0x46U >> (uStack_13c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_148);
  }
  if ((0x46U >> (uStack_14c & 0x1f) & 1) != 0) {
    func_0x000140001410(&uStack_158);
  }
  puRam0000000140657668 = (undefined8 *)uStack_c0;
  return;
}
END DECOMPILED REFERENCE */
