#!/usr/bin/env python3
"""
slot_map.py -- cross-reference runtime variable slots (uRam...) in the FNAFN
decompile with every piece of static evidence that could identify them.

Why this exists
---------------
PORTING.md: variable identity for the fast-path slots (uRam00000001405cxx)
cannot be read statically because the slots are patched at load time from
data.win's variable table, and the FNAFN data.win is a YYC build's data file
with NO VARI chunk (verified 2026-09-30 -- chunks are GEN8..AUDO, no
VARI/CODE/FNDR). The exe that owned the patched slots (FNAFN.exe) is no
longer on this machine either (Downloads wiped; see KINCAID-HANDOFF-V3).

So the only static evidence available in the repo is co-occurrence inside a
function:
  * id-fetch patterns  -- (**(code **)(*param_1 + 0x10))(param_1, 0x18xxx)
                          (instance variable fetch by registry id) and
                          (**(code **)(*plRam000000014065e080 + 8))(plRam...,
                          0x18xxx) (global/function fetch),
  * builtin_ids.json   -- id -> name (variables AND functions share the
                          registry id space),
  * read/write helper  -- func_...15be60 = variable read (+compare),
                          func_...15f1a0 / func_...160140 = variable write /
                          builtin property write.

This script scans gml_all_414_decompiled.annotated.c per function and emits
SLOT-MAP.md: for every uRam slot, which functions touch it, how often it is
read vs written, and which registry ids are fetched in those same functions
with a name candidate from builtin_ids.json. It deliberately does NOT guess:
it reports evidence; the conclusion belongs to the porting session.

Usage:
    python3 slot_map.py
"""

import json
import re
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent
SRC = REPO / "gml_all_414_decompiled.annotated.c"
IDS = REPO / "builtin_ids.json"
OUT = REPO / "SLOT-MAP.md"

FUNC_HEADER = re.compile(
    r"^// #### (gml_\S+)\s+va=0x([0-9a-f]+)\s+size=(\d+)", re.M)
SLOT_RE = re.compile(r"uRam0000000(14[0-9a-f]{6,8})")
ID_RE = re.compile(r"0x1[0-9a-f]{4}\b")
READ_RE = re.compile(r"func_0x00014015be60\([^;]*?\buRam0000000(14[0-9a-f]+)")
WRITE_RE = re.compile(
    r"func_0x000140(?:15f1a0|160140|15fea0)\([^;]*?\buRam0000000(14[0-9a-f]+)")


def load_ids():
    idmap = json.loads(IDS.read_text())
    return {int(k, 16): v for k, v in idmap.items()}


def main():
    text = SRC.read_text(errors="replace")
    ids = load_ids()

    # Split into functions.
    headers = list(FUNC_HEADER.finditer(text))
    print("functions: %d" % len(headers))

    slot_funcs = defaultdict(set)          # slot -> {func names}
    slot_reads = defaultdict(int)          # slot -> read-helper count
    slot_writes = defaultdict(int)         # slot -> write-helper count
    slot_ids = defaultdict(lambda: defaultdict(int))  # slot -> id -> count

    for i, m in enumerate(headers):
        fname = m.group(1)
        start = m.end()
        end = headers[i + 1].start() if i + 1 < len(headers) else len(text)
        body = text[start:end]

        # ids actually fetched in this function (any 0x186xx/0x187xx/0x188xx
        # appearing in a fetch-call argument position; we keep it broad and
        # filter to known ids)
        fetched = set()
        for im in ID_RE.finditer(body):
            v = int(im.group(0), 16)
            if 0x186a0 <= v <= 0x18848 and v in ids:
                fetched.add(v)

        for sm in SLOT_RE.finditer(body):
            slot = sm.group(1)
            if slot.startswith("14065"):
                continue  # runner context globals (self push / current inst)
            slot_funcs[slot].add(fname)
            for im in fetched:
                slot_ids[slot][im] += 1

        for rm in READ_RE.finditer(body):
            if not rm.group(1).startswith("14065"):
                slot_reads[rm.group(1)] += 1
        for wm in WRITE_RE.finditer(body):
            if not wm.group(1).startswith("14065"):
                slot_writes[wm.group(1)] += 1

    lines = []
    lines.append("# SLOT-MAP.md -- runtime variable slots vs static evidence")
    lines.append("")
    lines.append("Generated by `slot_map.py` from"
                 " `gml_all_414_decompiled.annotated.c` + `builtin_ids.json`.")
    lines.append("See header of `slot_map.py` for why names cannot be read")
    lines.append("statically (YYC data.win has no VARI chunk; FNAFN.exe with")
    lines.append("the load-time slot patch is not on this machine).")
    lines.append("")
    lines.append("Evidence per slot: functions touching it, read/write helper")
    lines.append("counts, and registry ids fetched in the SAME function")
    lines.append("(co-occurrence, NOT proof). Proven names so far, from")
    lines.append("PORTING.md: `0x18719 fading`, `0x18793 toggle`,")
    lines.append("`0x186d5 Scr_Camera_Update`, `0x18703 customfunct_game_save`.")
    lines.append("")
    lines.append("| slot | funcs | reads | writes | co-fetched ids (count) |")
    lines.append("|---|---|---|---|---|")
    for slot in sorted(slot_funcs,
                       key=lambda s: -sum(slot_ids[s].values())):
        co = slot_ids[slot]
        co_s = ", ".join(
            "`0x%05x %s`x%d" % (i, ids[i], c)
            for i, c in sorted(co.items(), key=lambda kv: -kv[1])[:8])
        lines.append("| uRam0000000%s | %d | %d | %d | %s |" % (
            slot, len(slot_funcs[slot]), slot_reads.get(slot, 0),
            slot_writes.get(slot, 0), co_s or "-"))
    lines.append("")
    lines.append("## How to turn co-occurrence into a name")
    lines.append("")
    lines.append("1. Open the function in the annotated C.")
    lines.append("2. If the same variable is fetched by id in ONE function")
    lines.append("   (slow path: fetch id, then write through the returned")
    lines.append("   pointer) and by slot in ANOTHER, the runtime slot value")
    lines.append("   equals the id's registered variable -- name follows the")
    lines.append("   id. Verify the fetch is a VARIABLE fetch (`+0x10` on the")
    lines.append("   instance vtable) and not a function call (`+8` on")
    lines.append("   `plRam000000014065e080`).")
    lines.append("3. Property writes via `func_...160140` are builtins")
    lines.append("   (image_*, x, y...): use argument shape, not ids.")
    lines.append("4. If still ambiguous, keep the `variable_resolve_placeholder`")
    lines.append("   convention + `TODO(calibrate)` as in the ported files.")
    lines.append("")
    lines.append("## Rebuilding the ground truth (needs FNAFN.exe)")
    lines.append("")
    lines.append("The load-time patcher writes registered variables into the")
    lines.append("slots in registry order. With the exe recovered, dump the")
    lines.append("registration table (source of builtin_ids.json), sort the")
    lines.append("slot addresses ascending, and align with the variable-id")
    lines.append("order to obtain the full static mapping in one step. Then")
    lines.append("re-run this script and replace the co-occurrence column")
    lines.append("with exact names.")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print("wrote %s (%d slots)" % (OUT.name, len(slot_funcs)))


if __name__ == "__main__":
    main()
